import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mobilytix Trigger Generator',
  description: 'Generated by Mobilytix',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script type="text/javascript" src="./webpush.js"></script>
        {children}
      </body>
    </html>
  )
}
