import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mobilytix Trigger Generator',
  description: 'Generated by Mobilytix',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script id="webpush-script" strategy="beforeInteractive">
          {
            `
          var _at = {};
          var u = "//mdm-gcdn.s3.amazonaws.com/non-prod/";
          _at.domain = "mocktel-trigger.netlify.app";
          _at.idSite = "36f85f40-3c19-11ee-a8a6-955d7af18de5";

          (function() {
            var d = document;
          var g = d.createElement('script');
          var s = d.getElementsByTagName('script')[0];
          g.type = 'text/javascript'
          g.async = true
          g.defer = true
          g.src = u + "script-mdm.js";
          s.parentNode.insertBefore(g, s);

         })();
            `
          }
        </Script>
        {children}
      </body>
    </html>
  )
}
